racerfly/Ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('a1**sam**!!**/admin/', admin.site.urls),
    path('', include('racerfly.urls')),
]
#if settings.DEBUG:
# if True:
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

racerfly/racerfly/urls.py
from django.urls import path
from . import views

app_name = 'racerfly'

urlpatterns = [
	path('', views.home, name='home'),

	## AUTHENTICATION
	path('ajax_generate_code/', views.ajax_generate_code, name='ajax_generate_code'),
	path('register/', views.register, name='register'),
	path('login/', views.login, name='login'),
	path('forgot_password_index/', views.forgot_password_index, name='forgot_password_index'),
	path('reset_password/', views.reset_password, name='reset_password'),
	path('logout/', views.logout, name='logout'),

	## CONTENTS
	path('tnc/', views.tnc, name='tnc'),
	path('privacy_policy/', views.privacy_policy, name='privacy_policy'),
	path('aboutUs/', views.aboutUs, name='aboutUs'),
	path('contactus/', views.cont_us, name='cont_us'),
	path('category/<int:category_id>/', views.series, name='series'),
	path('category/<int:category_id>/<int:series_id>/', views.items, name='items'),
	path('category/<int:category_id>/<int:series_id>/<int:item_id>/', views.buyItem, name='buyItem'),

	## User account
	path('dashboard/', views.dashboard, name='dashboard'),
	path('track/', views.track_order, name='track_order'),
	path('cart/', views.cart, name='cart'),
	path('verify_payment/', views.verify_payment, name='verify_payment'),

	## Payments
	path('payment_success/', views.payment_success, name='payment_success'),
	path('payment_failure/', views.payment_failure, name='payment_failure'),


	### Upload Files
	path('upload_123/', views.upload_file, name='upload_file'),

	# path('saveSuggestion/<int:url>/', views.saveSuggestion, name='saveSuggestion'),
]

racerfly/racerfly/forms.py
from django import forms
from .models import *

class RegisterForm(forms.ModelForm):
	class Meta:
		model = Customer
		fields = ['name', 'email', 'password', 'city']
		widgets = {
			'password': forms.PasswordInput(),
		}

class LoginForm(forms.ModelForm):
	class Meta:
		model = Customer
		fields = ['email', 'password']
		widgets = {
			'password': forms.PasswordInput(),
		}

racerfly/racerfly/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from datetime import datetime
from .forms import *
from .models import *
from .decorators import customer_login_required
import random
from django.core.mail import EmailMultiAlternatives
from django.template.loader import render_to_string
from Ecommerce.settings import EMAIL_HOST_USER, SENDGRID_API_KEY
from django.utils.html import strip_tags
import razorpay
import hmac, hashlib
import string
from decimal import Decimal
from racerfly.templatetags.tags import *
import os
from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import Mail
# Create your views here.

## UTILS
# dollarToRs = Util.objects.get(name='DollarToRs').float_value


########## TEST KEYS
# APP_ID = 'rzp_test_VTMvgmRWpMvYip'
# APP_SECRET = '399xvFLXfpeXjNpQ8B0W0wDU'

########## LIVE KEYS
APP_ID = 'rzp_live_46KNgnEVu2I48A'
APP_SECRET = 'Y8zoPpXjNyJimVmDvyvqvxwb'


razorpay_client = razorpay.Client(auth=(APP_ID, APP_SECRET))
# razorpay_client.set_app_details({"title" : "Racerfly", "version" : "2.0.2"})
# razorpay_client = razorpay.Client(auth=("<YOUR_API_KEY>", "<YOUR_API_SECRET>"))

def get_user(request):
	user = Customer.objects.get(id=request.session['user_id'])
	return user

def randomStringDigits(stringLength):
    """Generate a random string of letters and digits """
    lettersAndDigits = string.ascii_letters + string.digits
    return ''.join(random.choice(lettersAndDigits) for i in range(stringLength))

def addPriceToCart(item, gst):

	return Decimal(float(item.item.priceDollar)*float((100-item.item.discount)/100)*float(item.quantity)*(1+gst/100))

def addToCart(request, item, qty, gst, special_requirements=None):
	
	user = get_user(request)

	# Create new ItemCart
	new_itemcart = ItemCart(
		item = item,
		quantity = int(qty),
		special_requirements = special_requirements,
	)
	new_itemcart.save()

	# print('\n\n' + str(addPriceToCart(new_itemcart, gst)) + '\n\n')

	# Update user cart
	if user.cart:
		user.cart.items.add(new_itemcart)
		user.cart.totPrice += addPriceToCart(new_itemcart, gst)# Decimal(float(new_itemcart.item.priceDollar)*float((100-new_itemcart.item.discount)/100)*float(new_itemcart.quantity)*(gst/100))
		user.cart.save()
		user.save()
	else:
		new_cart = Cart(totPrice=addPriceToCart(new_itemcart, gst))
		new_cart.save()
		new_cart.items.add(new_itemcart)
		user.cart = new_cart
		user.save()

def addToFav(request, item):
	user = get_user(request)
	user.favourites.add(item)
	user.save()

def sendMailSendGrid(request, to_email, subject, html_content):

	message = Mail(
	    from_email= 'RacerFly <sales@racerfly.com>',
	    to_emails=to_email,
	    subject=subject,
	    html_content=html_content)
	# print(message)
	try:
	    sg = SendGridAPIClient('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')
	    # sg = SendGridAPIClient(os.environ.get('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'))
	    response = sg.send(message)
	    # print(response.status_code)
	    # print(response.body)
	    # print(response.headers)
	except Exception as e:
	    print(str(e))

###### HOME

def home(request):
	categories = Category.objects.all()

	auth = False
	if ('user_id' in request.session) and Customer.objects.filter(id=request.session['user_id']).exists():
		auth = True
		user = get_user(request)
		return render(request, 'racerfly/home.html', {'auth': auth, 'user': user, 'categories': categories})
	elif ('user_id' in request.session) and (not Customer.objects.filter(id=request.session['user_id']).exists()):
		del request.session['user_id']
	return render(request, 'racerfly/home.html', {'auth': auth, 'categories': categories})

######### AUTHENTICATION

def ajax_generate_code(request):
	# print(request.GET)
	for x in request.GET:
		if x!='_':
			email = x

			## Generate Code and save it in a session
			request.session['code'] = random.randint(100000, 999999)
			# print(request.session['code'])

			## Send email Functionality
			html_content = render_to_string('racerfly/auth/verify_email.html', {'code': request.session['code']})
			sendMailSendGrid(request, email, 'Verify Email', html_content)

			# text_content = "Your Email Verification Code is " + str(request.session['code'])
			# msg = EmailMultiAlternatives('Verify Email', text_content, EMAIL_HOST_USER, [email])
			# msg.send()

			return HttpResponse("success")

def password_check(passwd): 
      
    SpecialSym =['$', '@', '#', '%'] 
    error = None
      
    if len(passwd) < 6: 
        error = 'length should be at least 6'
          
    if len(passwd) > 20: 
        error = 'length should be not be greater than 8'
          
    # if not any(char.isdigit() for char in passwd): 
    #     error = 'Password should have at least one numeral'
          
    # if not any(char.isupper() for char in passwd): 
    #     error = 'Password should have at least one uppercase letter'
          
    # if not any(char.islower() for char in passwd): 
    #     error = 'Password should have at least one lowercase letter'
          
    # if not any(char in SpecialSym for char in passwd): 
    #     error = 'Password should have at least one of the symbols $,@,#'

    if error:
    	return error

def register(request):
	categories = Category.objects.all()

	if request.method=='POST':
		if ('password' in request.POST) and ('confirm_password' in request.POST) and request.POST['password']!=request.POST['confirm_password']:
			error = "Passwords didn't match !"
			return render(request, 'racerfly/auth/register.html', {'categories': categories, 'error': error})
		if Customer.objects.filter(email=request.POST['email']).exists():
			error = "This email is already registered with us."
			return render(request, 'racerfly/auth/register.html', {'categories': categories, 'error': error})
		error = password_check(request.POST['password'])
		if error:
			return render(request, 'racerfly/auth/register.html', {'categories': categories, 'error': error})

		## Check Verification Code
		if (not 'code' in request.POST) or (not 'code' in request.session) or (not request.POST['code']==str(request.session['code'])):
			error = "Invalid Verification Code !"
			return render(request, 'racerfly/auth/register.html', {'categories': categories, 'error': error})


		t_password_hash = hashlib.sha256()
		t_password_hash.update((request.POST['password']).encode())
		new_user = Customer(
			name=request.POST['name'],
			email = request.POST['email'],
			phone_no = request.POST['phone_no'],
			city = request.POST['city'],
			password = t_password_hash.hexdigest(),
		)
		#new_user.password = str(hash(request.POST['password']))
		new_user.save()
		return redirect('racerfly:login')
	return render(request, 'racerfly/auth/register.html', {'categories': categories})

def login(request):
	categories = Category.objects.all()
	if 'user_id' in request.session:
		return redirect('racerfly:home')
	form = LoginForm()
	if request.method=='POST':
		t_password_hash = hashlib.sha256()
		t_password_hash.update((request.POST['password']).encode())
		if Customer.objects.filter(email=request.POST['email'], password=t_password_hash.hexdigest()).exists():
			user = Customer.objects.get(email=request.POST['email'])
		# else if Customer.objects.filter(phone_no=int(request.POST['email']), password=str(hash(request.POST['password']))).exists():
		# 	user = Customer.objects.get(phone_no=int(request.POST['email']), password=str(hash(request.POST['password'])))
			request.session['user_id'] = user.id
			if 'url_to_go' in request.session:
				return redirect(request.session['url_to_go'])
			return redirect('racerfly:home')
	return render(request, 'racerfly/auth/login.html', {'form': form, 'categories': categories})

def forgot_password_index(request):

	sent = None
	if request.method=='POST':
		if not Customer.objects.filter(email=request.POST['email']).exists():
			error = 'We could not find an account registered with this email.'
			return render(request, 'racerfly/auth/forgot_password_index.html', {'error': error})

		email = request.POST['email']
		request.session['forgot_password_user_id'] = Customer.objects.get(email=email).id
		html_content = render_to_string('racerfly/auth/forgot_password_mail_content.html')
		sendMailSendGrid(request, request.POST['email'], 'Reset Password', html_content)
		# text_content = strip_tags(html_content)
		# msg = EmailMultiAlternatives('reset password', text_content, EMAIL_HOST_USER, [request.POST['email']])
		# msg.attach_alternative(html_content, 'text/html')
		# msg.send()
		sent = True
	return render(request, 'racerfly/auth/forgot_password_index.html', {'sent': sent})

def reset_password(request):
	categories = Category.objects.all()
	success = False
	if request.method=='POST':
		error = password_check(request.POST['password'])
		if error:
			return render(request, 'racerfly/auth/reset_password.html', {'error': error})

		customer = Customer.objects.get(id=request.session['forgot_password_user_id'])
		t_password_hash = hashlib.sha256()
		t_password_hash.update((request.POST['password']).encode())
		customer.password = t_password_hash.hexdigest()
		customer.save()
		success = True
		del request.session['forgot_password_user_id']
	return render(request, 'racerfly/auth/reset_password.html', {'success': success})

@customer_login_required
def logout(request):
	categories = Category.objects.all()
	del request.session['user_id']
	if 'url_to_go' in request.session:
		del request.session['url_to_go']
	return redirect('racerfly:login')



######## CONTENTS
@customer_login_required
def dashboard(request):
	gst = Util.objects.get(name='GST').float_value
	categories = Category.objects.all()
	user = get_user(request)
	if request.method=='GET':
		if 'param' in request.GET:
			item = Item.objects.get(id=int(request.GET['param']))
			new_itemcart = ItemCart(
				item = item,
				quantity = 1
			)
			new_itemcart.save()

			if user.cart:
				user.cart.items.add(new_itemcart)

racerfly/racerfly/templates/racerfly/dashboard.html
{% extends 'baseIn.html' %}

{% block body %}
{% load static %}


    <link rel="stylesheet" href="{% static 'utils/style_dash.css' %}">

<div class="head_cont">
            <div class="racerFly">
                <!-- Link to home -->
                <a href="{% url 'racerfly:home' %}">
                    <img src="{% static 'images/final_logo.png' %}" alt="">
                </a>
            </div>
            <div class="usr_data">
                <div class="usrimg">
                    <!-- User Image -->
                    <img src="{% static 'images/one.png' %}" alt="">
                </div>
                <div class="usrinfo">
                    <div class="usrname">
                        <h2>{{ user.name }}</h2>
                    </div>
                    <div class="usremail">
                        {{ user.email }}
                        <!-- dummyuser<span>@gmail.com</span> -->
                        
                    </div>
                    
                    {% if user.phone_no %}
                    <div class="usrmobile">
                        {{ user.phone_no }}
                        <!-- <b>+91</b><span>0000000000</span> -->
                     </div>
                    {% endif %}

                </div>
            </div>
        </div>
        <div class="data_cont">
            <div class="left cont">
                <div class="opt" onclick="gjbkkjh(1,this);">
                    Your Orders
                </div>
                <div class="opt" onclick="gjbkkjh(2,this);">
                    Your Wish List
                </div>
                <div class="opt" onclick="gjbkkjh(3,this);">
                    Edit Account Details
                </div>
                <div class="opt"  onclick="gjbkkjh(4,this);">
                    Notifications
                </div>
                <div class="opt" onclick="gjbkkjh(5,this);">
                    Settings
                </div>
                <div class="opt" onclick="gjbkkjh(6,this);">
                    Help
                </div>
                <div class="contt"></div>
            </div>
            <div class="mid cont">
                <div id="order">
                    <h2>Your Orders</h2>
                    <div>
                        <table>
                            <tr>
                                <th>Product Name</th>
                                <th>Order ID</th>
                                <th>Order Time</th>
                                <th>Details</th>
                            </tr>

                            {% for order in user.my_orders.all reversed %}
                                <tr>
                                    <td>
                                        <!-- Link to Product description Page -->
                                        <a href="{% url 'racerfly:buyItem' order.item.series.category.id order.item.series.id order.item.id %}">
                                            <b>{{ order.item.name }}</b>
                                        </a>
                                    </td>
                                    <td>
                                        {{ order.order_id }}
                                    </td>
                                    <td>
                                        {{ order.order_time }}
                                    <!-- {% if order.delivered %}
                                        Package has already delivered.
                                    {% else %}
                                        Package is on the way.
                                    {% endif %} -->
                                    </td>
                                    <td>
                                        <!-- Link to Product Delivery Track Page for delivered and not delivered product-->
                                        {% if order.delivered %}
                                        <a href="{% url 'racerfly:track_order' %}?search={{order.order_id}}">
                                            View delivery log
                                        </a>
                                        {% else %}
                                        <a href="{% url 'racerfly:track_order' %}?search={{order.order_id}}" target="_blank">
                                            Track package
                                        </a>
                                        {% endif %}
                                    </td>
                                </tr>
                            {% endfor %}
                        </table>
                    </div>
                </div>

                <div id="wish_list">
                    <h2>Wish List</h2>
                    <div>
                        <table>
                            <tr>
                                <th>Product Name</th>
                                <th>Order now</th>
                            </tr>


                            {% for wish_item in user.favourites.all %}
                            <tr>
                                <td>
                                    <!-- Link to Product description Page -->
                                    <a href="{% url 'racerfly:buyItem' wish_item.series.category.id wish_item.series.id wish_item.id %}">
                                        <b> {{ wish_item.name }} </b>
                                    </a>
                                </td>
                                <td>
                                    <!-- Link to Product Delivery Track Page for delivered and not delivered product-->
                                    {% if not wish_item.sold_out %}
                                    <a href="{% url 'racerfly:dashboard' %}?param={{wish_item.id}}">
                                        Add To Cart
                                    </a>
                                    {% else %}
                                    <abbr title="Sold Out">Add To Cart</abbr>
                                    {% endif %}
                                </td>
                            </tr>
                            {% endfor %}
                            <!-- 
                            <tr>
                                <td>
                                    <a href="">
                                        <b>Motors by MDMN clear shaft</b>
                                    </a>
                                </td>
                                <td>
                                    <a href="">
                                        Order now
                                    </a>
                                </td>
                            </tr>
                                 -->            
                        </table>
                    </div>
                </div>
                <div id="edit">
                    <h2>Edit Details</h2>
                    <div>
                        <b>Nothing to show here ...</b>
                        <h4>We will surely try to make it workable in few days.</h4>
                    </div>
                </div>
                <div id="notification">
                    <h2>Your Notifications</h2>
                    <div>
                        <b>Nothing to show here ...</b>
                        <h4>We will surely try to make it workable in few days.</h4>
                    </div>
                </div>
                <div id="setting">
                    <h2>Your Settings</h2>
                    <div>
                        <b>Nothing to show here ...</b>
                        <h4>We will surely try to make it workable in few days.</h4>
                    </div>
                </div>
                <div id="help">
                    <h2>Help</h2>
                    <div>
                        <b>Nothing to show here ...</b>
                        <h4>We will surely try to make it workable in few days.</h4>                
                    </div>
                </div>
            </div>
        </div>

        <script src="{% static 'utils/script_dash.js' %}"></script>

        <script>
            window.onload = function(){
                        document.body.setAttribute("m","o");
                        document.body.setAttribute("h","o");}
        </script>

{% endblock %}

racerfly/racerfly/templates/racerfly/home.html
{% extends auth|yesno:'baseIn.html,baseOut.html' %}

{% block body %}

{% load static %}
           <div class="go">
                <div style="width:100%; font-size:16px;text-align: center; padding:25px 0 15px 0; background: #8ae8a9;  font-family: 'Montserrat'; color:#121212;line-height:20px; letter-spacing:1.5px;text-shadow:0 0px 1px #9a9;font-weight:700;">
			<div> 
<!-- 				Good evening, do not panic this is just a test-->
        			<div>Racerfly brings Fully Autonomous Sprayer Drones in India</div>
				<div style="padding:10px 0;">
<!-- 		Link to drones.racerfly.com			 -->
					<a href="https://drones.racerfly.com" target="_blank" style="text-decoration: none;">
						<div id="link_to_drones" style="width: 200px;padding: 10px 0;background: #f8ec61;color: #000;margin: 0 auto;color:#010101;text-shadow: none; box-shadow: inset 0 0 0 2px rgba(0,0,0,0.2);">Click Here</div>                       
					</a>					
				</div>
		    	</div>
		</div>
	
		   
                <div class="frame" style="height:300px;">
                        <div class="now" val zero style="height:300px;">
                            <img src="{%static 'images/banner3.png' %}" alt="">
                            <div class="img_text">
	                            <b><div class="name" val="Product name"></div></b>
	                            <a href="#">
	                                <div class="specifications" val="specifications"></div>
	                            </a>
                        	</div>
                        </div>
                        <div class="now"  val="hid" zero="0" style="height:300px;">
                            <img src="{%static 'images/banner4.png' %}" alt=""  >
                            <div class="img_text">
                                <b><div class="name" val="Product name"></div></b>
                                <a href="#">
                                    <div class="specifications" val="specifications"></div>
                                </a>
                            </div>
                        </div>
                        <!-- <div class="now" val="hid" zero="0"  style="height:230px;" >
                                <img src="{%static 'images/long.jpg' %}"  alt="">
                                <div class="img_text">
                                    <b><div class="name" val="Product name"></div></b>
                                    <a href="">
                                        <div class="specifications" val="specifications"></div>
                                    </a>
                                </div>
                            </div>
                            <div class="now"  val="hid" zero="0"  style="height:230px;" >
                                    <img src="{%static 'images/long.jpg' %}" alt="">
                                    <div class="img_text">
                                        <b><div class="name" val="Product name"></div></b>
                                        <a href="">
                                            <div class="specifications" val="specifications"></div>
                                        </a>
                                    </div>
                                </div> -->
                                    <div class="movement">
                            <div class="product">
                                <a id="product" href="#">
                                    <div></div>
                                </a>
                            </div>
                            <div class="pre">
                                    <svg width="30" height="30" viewBox="0 0 95 95">
                                            <g>
                                                <line x1="18" y1="50" x2="43" y2="30" stroke="#555" stroke-width="5" stroke-linecap="round"></line>
                                                <line x1="18" y1="50" x2="43" y2="70" stroke="#555" stroke-width="5" stroke-linecap="round"></line>
                                                <line x1="18" y1="50" x2="75" y2="50" stroke="#555" stroke-width="5" stroke-linecap="round"></line>
                                            </g>
                                    </svg>
                            </div>
                            <div class="next">
                                    <svg width="30" height="30" viewBox="0 0 95 95">
                                            <g style="transform:rotateZ(180deg); transform-origin:center;">
                                                <line x1="18" y1="50" x2="43" y2="30" stroke="#555" stroke-width="5" stroke-linecap="round"></line>
                                                <line x1="18" y1="50" x2="43" y2="70" stroke="#555" stroke-width="5" stroke-linecap="round"></line>
                                                <line x1="18" y1="50" x2="75" y2="50" stroke="#555" stroke-width="5" stroke-linecap="round"></line>
                                            </g>
                                    </svg>
                            </div>

                        </div>
                        <diV class="dir">
                            <div onclick="roll(1)"><div is="1"></div></div>
                            <div onclick="roll(2)"><div is="0"></div></div>
                            <!-- <div onclick="roll(3)"><div is="0"></div></div>
                            <div onclick="roll(4)"><div is="0"></div></div> -->
                        </diV>
                </div>
                <div class="specs">
                    <div class="data">
                            <h2 val="Categories" style="margin:0;"> </h2>
                            <hr style="max-width:300px; margin-bottom:20px;">
                            <div class="main_div">
                            	{% for category in categories %}
                                <div class="subdiv">
                                        <div class="subbdiv">
                                                <a href="{% url 'racerfly:series' category.id %}">
                                                    <div>
                                                    	{% if category.image %}
                                                        <img src="{{category.image.url}}" alt="">
                                                        {% else %}
                                                        <img src="{% static 'images/image.jpg' %}" alt="">
                                                        {% endif %}
                                                        <div specs="{{category.name}}" style="box-shadow:inset 0 0 10px 0 rgba(0,0,0,0.2),0 0 1px 0 rgba(0,0,0,0.2); border-radius:5px;"></div>
                                                    </div>
                                                </a>
                                            </div>                           
                                </div>
                                {% endfor %}
                    </div>
                </div>
           </div>
           <div class="specs">
               <div class="data">
                   <div style="color:#444; font-size:22px; font-weight: 600; font-family:'Montserrat',sans-serif; text-align: center;">
                        <p style="margin:5px 0;">Looking for any ITEM other than these or Bulk Order or Advance orders?</p>
                        <p style="margin:5px 0;">We can fullfil your special needs.</p>
                        <p style="margin:5px 0;">Please, let us know " <a href="{% url 'racerfly:cont_us' %}">HERE</a> ". </p>
                    </div>
               </div>
           </div>

       <script>
        function f (){
                if(!!document.getElementsByClassName("now")[0]){
                    var a = 0;
                    for(var i in document.getElementsByClassName("now")){
                        if(!document.getElementsByClassName("now")[i].getAttribute("val")){
                            a = document.getElementsByClassName("now")[i].getElementsByTagName("img")[0].height;
                            break;
                    }
                }
                    document.getElementsByClassName("frame")[0].style="height:"+(a+80)+"px";
                    document.getElementsByClassName("movement")[0].style="height:"+(a+40)+"px";
                    for(var i in document.getElementsByClassName("now")){
                        document.getElementsByClassName("now")[i].style="height:"+(a+40)+"px";
                    }
                }
        }
        try{f();}catch(e){};
    </script>
{% endblock %}

racerfly/racerfly/templates/racerfly/order_placed_mail.html
{% load tags %}

Hi {{ user.name }}, your order is booked with us with booking ids as shown below with the items.


{% for item in itemsToShow %}
<div> 
	{{ item.item.name }} 
	<br>
	<b>Quantity : </b> {{ item.quantity }} 
	<br>
	<b> Price : </b> {{ item.item.priceDollar|multiply:dollarToRs|multiply:item.quantity }}  
	<br>
	<i><b>Order ID</b></i> {{ item.order_id }} 
</div>
<br>
{% endfor %}

<br>
<br>
<div> <b>GST</b> : {{ gst_price }} </div>
<div> <b>Delivery Charge</b> : {{ delivery_charge }} </div>
<br>
<div> <b><i>Grand Total </i></b> : {{ grandTotal }} </div>


You can also track your orders from our website.
THANK YOU FOR ORDERING WITH RACERFLY.
KEEP UPDATED WITH US FOR OUR NEW SCHEMES AND PROGRAMS.

racerfly/racerfly/templates/racerfly/payment_failure.html
<div style="padding:20px; max-width:600px; margin:0 auto;"><h1 style="margin:0; color:#f66;">Sorry, Something went wrong !</h1><br/>Go back to your <a href="{% url 'racerfly:cart' %}">Cart</a></div>